format_version: 2
pipelines:
  PackerCommit:
    group: TerraformPipeline
    materials:
      backend:
        git: http://git-repo:3000/gogs/terraform-pipeline-packer.git
        branch: master
    stages:
      - Validate:
          jobs:
            Validate:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - -c
                    - packer validate nginx.json
      - Build:
          jobs:
            Build:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                    - -c
                    - BUILD_LABEL=${GO_PIPELINE_LABEL} packer build nginx.json
